### ISSUE TITLE
Deep press causes issues with double_tap_action and tap_action.

### ISSUE THREAD

**Issue by ASNNetworks** [roflcoopter/deep-press#6]
Hi,

I noticed some weird behaviour with RomRiders button card since his last update. After testing extensively, we found out it's due to deep_press. This issue is also present with core button card. See this issue: https://github.com/custom-cards/button-card/issues/399

Please let me know what I can do to help :)!

**Comment by roflcoopter** [comment]
Sorry for not getting back to you earlier on the other thread.

I just published a small update, can you see if that works for you? I have limited time for testing right now so it might not have covered all your usecases.

**Comment by roflcoopter** [comment]
I messed up my releases a bit, 2.1.1-1 should be available now

**Comment by ASNNetworks** [comment]
I tried the update (also the 2.1.1-1 after that). Didn't work unfortunately. I also deleted the component and re-installed through HACS (to make sure the latest is used) and cleared cache after that. Doesn't work also. Let me know when you have the time and pushed a new update, so I can test and get back to you :)

**Comment by roflcoopter** [comment]
Can you post a minimal config example so i can reproduce the error? I have a card that has both tap_action and double_tap_action defined and it works for me

**Comment by ASNNetworks** [comment]
Hi, I created a short button to test this (this is core button). And I can reproduce this issue on my iPhone. I created this code below so the test is easier (so I can see the light actually turn on or not). 

```
deep_press: true
entity: light.woonkamer_bollen
tap_action:
  action: call-service
  service: light.turn_on
  service_data:
    entity_id: light.woonkamer_bollen
double_tap_action:
  action: call-service
  service: light.turn_off
  service_data:
    entity_id: light.woonkamer_bollen
hold_action:
  action: more-info
type: button
```

I'm running iOS14.2 on iPhone XS Max. When I tap once on the icon, the light turns off (envoking the double_tap_action). Doing a double tap, does that twice. Single tap doesn't work, unless I remove double_tap_action or deep_press.
