### ISSUE TITLE
Deep press doesn't render button_card_templates

### ISSUE THREAD

**Issue by smitt04** [roflcoopter/deep-press#8]
When using a button_card template with javascript the `[[[ <javascript> ]]]` doesn't render properly.

An example config:
```yaml
light_popup:
  deep_press: false
  hold_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      hide_header: false
      title: |
        [[[ return entity.attributes.friendly_name ]]]
      card:
        type: entities
        entities:
          - type: "custom:light-popup-card"
            entity: |
              [[[ return entity.entity_id ]]]
            icon: none
            fullscreen: false
            brightnessWidth: 130px
            brightnessHeight: 360px
            borderRadius: 1.7em
            sliderColoredByLight: true
            sliderTrackColor: "rgba(25, 25, 25, 0.9)"
```
